<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <DebugType>embedded</DebugType>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <VersionPrefix>1.0.75</VersionPrefix>
    <Authors>LilacMacro contributors</Authors>
    <Copyright>Copyright 2026 LilacMacro contributors</Copyright>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/LeniLilac/LilacMacro</RepositoryUrl>
    <PackageLicenseExpression>PolyForm-Noncommercial-1.0.0</PackageLicenseExpression>
  </PropertyGroup>
</Project>
