<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>LilacMacro.Windows</RootNamespace>
    <AssemblyName>LilacMacro.Windows</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LilacMacro.Core\LilacMacro.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D11" />
  </ItemGroup>
</Project>
