<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>LilacMacro.SessionSetup</RootNamespace>
    <AssemblyName>LilacMacro.SessionSetup</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LilacMacro.Core\LilacMacro.Core.csproj" />
    <ProjectReference Include="..\LilacMacro.Windows\LilacMacro.Windows.csproj" />
  </ItemGroup>
</Project>
